/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package polije.views;

import java.awt.Image;
import javax.swing.table.DefaultTableModel;
import polije.service.PassienServiceImpl;
import polije.service.PassienServiceInterface;

/**
 *
 * @author bacht
 */
public class CekKondisi extends javax.swing.JFrame {
    /**
     * Creates new form CekKondisi
     */
    DefaultTableModel model = new DefaultTableModel();
    private PassienServiceInterface passien;
    
    public CekKondisi() {
        initComponents();
        this.passien = new PassienServiceImpl();
        this.passien.showPassien(tableKondisi);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dasar = new javax.swing.JPanel();
        panelCekKondisi = new javax.swing.JPanel();
        panelIdentitasPasien1 = new javax.swing.JPanel();
        logoIdentitasPasien1 = new javax.swing.JLabel();
        panelLabelIdentitas1 = new javax.swing.JPanel();
        labelIdentitasPasien1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKondisi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dasar.setBackground(new java.awt.Color(255, 255, 255));
        dasar.setMaximumSize(new java.awt.Dimension(1280, 720));
        dasar.setMinimumSize(new java.awt.Dimension(1280, 720));
        dasar.setPreferredSize(new java.awt.Dimension(1280, 720));

        panelCekKondisi.setBackground(new java.awt.Color(4, 30, 65));
        panelCekKondisi.setMaximumSize(new java.awt.Dimension(640, 720));
        panelCekKondisi.setMinimumSize(new java.awt.Dimension(640, 720));
        panelCekKondisi.setPreferredSize(new java.awt.Dimension(640, 720));

        panelIdentitasPasien1.setBackground(new java.awt.Color(66, 83, 109));

        logoIdentitasPasien1.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/polije/assets/Cek kondisi.png")).getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
        logoIdentitasPasien1.setMaximumSize(new java.awt.Dimension(80, 80));
        logoIdentitasPasien1.setMinimumSize(new java.awt.Dimension(80, 80));
        logoIdentitasPasien1.setPreferredSize(new java.awt.Dimension(80, 80));

        labelIdentitasPasien1.setBackground(new java.awt.Color(242, 255, 255));
        labelIdentitasPasien1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelIdentitasPasien1.setText("Cek Kondisi");

        javax.swing.GroupLayout panelLabelIdentitas1Layout = new javax.swing.GroupLayout(panelLabelIdentitas1);
        panelLabelIdentitas1.setLayout(panelLabelIdentitas1Layout);
        panelLabelIdentitas1Layout.setHorizontalGroup(
            panelLabelIdentitas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLabelIdentitas1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelIdentitasPasien1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelLabelIdentitas1Layout.setVerticalGroup(
            panelLabelIdentitas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLabelIdentitas1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelIdentitasPasien1)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelIdentitasPasien1Layout = new javax.swing.GroupLayout(panelIdentitasPasien1);
        panelIdentitasPasien1.setLayout(panelIdentitasPasien1Layout);
        panelIdentitasPasien1Layout.setHorizontalGroup(
            panelIdentitasPasien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdentitasPasien1Layout.createSequentialGroup()
                .addGroup(panelIdentitasPasien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIdentitasPasien1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelLabelIdentitas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIdentitasPasien1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(logoIdentitasPasien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIdentitasPasien1Layout.setVerticalGroup(
            panelIdentitasPasien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIdentitasPasien1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(logoIdentitasPasien1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLabelIdentitas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tableKondisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableKondisi);

        javax.swing.GroupLayout panelCekKondisiLayout = new javax.swing.GroupLayout(panelCekKondisi);
        panelCekKondisi.setLayout(panelCekKondisiLayout);
        panelCekKondisiLayout.setHorizontalGroup(
            panelCekKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekKondisiLayout.createSequentialGroup()
                .addGroup(panelCekKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCekKondisiLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(panelIdentitasPasien1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCekKondisiLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelCekKondisiLayout.setVerticalGroup(
            panelCekKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekKondisiLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(panelIdentitasPasien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dasarLayout = new javax.swing.GroupLayout(dasar);
        dasar.setLayout(dasarLayout);
        dasarLayout.setHorizontalGroup(
            dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dasarLayout.createSequentialGroup()
                .addGap(0, 640, Short.MAX_VALUE)
                .addComponent(panelCekKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dasarLayout.setVerticalGroup(
            dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dasarLayout.createSequentialGroup()
                .addComponent(panelCekKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekKondisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekKondisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekKondisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekKondisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekKondisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dasar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelIdentitasPasien1;
    private javax.swing.JLabel logoIdentitasPasien1;
    private javax.swing.JPanel panelCekKondisi;
    private javax.swing.JPanel panelIdentitasPasien1;
    private javax.swing.JPanel panelLabelIdentitas1;
    private javax.swing.JTable tableKondisi;
    // End of variables declaration//GEN-END:variables
}
