/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package polije.views;

import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import polije.service.PassienServiceImpl;
import polije.service.PassienServiceInterface;

/**
 *
 * @author bacht
 */
public class CekKondisi extends javax.swing.JFrame {
    /**
     * Creates new form CekKondisi
     */
    DefaultTableModel model = new DefaultTableModel();
    private PassienServiceInterface passien;
    
    public CekKondisi() {
        initComponents();
        this.passien = new PassienServiceImpl();
        this.passien.showPassien(tableKondisi);
        
    }
    
    public void refresh(){
        this.setVisible(false);
        CekKondisi kondisi = new CekKondisi();
        
        kondisi.setVisible(true);
        this.dispose();
//        this.passien.showPassien(tableKondisi);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dasar = new javax.swing.JPanel();
        panelCekKondisi = new javax.swing.JPanel();
        panelIdentitasPasien1 = new javax.swing.JPanel();
        logoIdentitasPasien1 = new javax.swing.JLabel();
        panelLabelIdentitas1 = new javax.swing.JPanel();
        labelIdentitasPasien1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKondisi = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dasar.setBackground(new java.awt.Color(255, 255, 255));
        dasar.setMaximumSize(new java.awt.Dimension(1280, 720));
        dasar.setMinimumSize(new java.awt.Dimension(1280, 720));
        dasar.setPreferredSize(new java.awt.Dimension(1280, 720));

        panelCekKondisi.setBackground(new java.awt.Color(4, 30, 65));
        panelCekKondisi.setMaximumSize(new java.awt.Dimension(640, 720));
        panelCekKondisi.setMinimumSize(new java.awt.Dimension(640, 720));
        panelCekKondisi.setPreferredSize(new java.awt.Dimension(640, 720));

        panelIdentitasPasien1.setBackground(new java.awt.Color(66, 83, 109));

        logoIdentitasPasien1.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/polije/assets/Cek kondisi.png")).getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT)));
        logoIdentitasPasien1.setMaximumSize(new java.awt.Dimension(80, 80));
        logoIdentitasPasien1.setMinimumSize(new java.awt.Dimension(80, 80));
        logoIdentitasPasien1.setPreferredSize(new java.awt.Dimension(80, 80));

        labelIdentitasPasien1.setBackground(new java.awt.Color(242, 255, 255));
        labelIdentitasPasien1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelIdentitasPasien1.setText("Cek Kondisi");

        javax.swing.GroupLayout panelLabelIdentitas1Layout = new javax.swing.GroupLayout(panelLabelIdentitas1);
        panelLabelIdentitas1.setLayout(panelLabelIdentitas1Layout);
        panelLabelIdentitas1Layout.setHorizontalGroup(
            panelLabelIdentitas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLabelIdentitas1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelIdentitasPasien1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelLabelIdentitas1Layout.setVerticalGroup(
            panelLabelIdentitas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLabelIdentitas1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelIdentitasPasien1)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelIdentitasPasien1Layout = new javax.swing.GroupLayout(panelIdentitasPasien1);
        panelIdentitasPasien1.setLayout(panelIdentitasPasien1Layout);
        panelIdentitasPasien1Layout.setHorizontalGroup(
            panelIdentitasPasien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdentitasPasien1Layout.createSequentialGroup()
                .addGroup(panelIdentitasPasien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIdentitasPasien1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelLabelIdentitas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIdentitasPasien1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(logoIdentitasPasien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIdentitasPasien1Layout.setVerticalGroup(
            panelIdentitasPasien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIdentitasPasien1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(logoIdentitasPasien1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLabelIdentitas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tableKondisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKondisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKondisiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKondisi);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polije/assets/home.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Home");

        javax.swing.GroupLayout panelCekKondisiLayout = new javax.swing.GroupLayout(panelCekKondisi);
        panelCekKondisi.setLayout(panelCekKondisiLayout);
        panelCekKondisiLayout.setHorizontalGroup(
            panelCekKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekKondisiLayout.createSequentialGroup()
                .addGroup(panelCekKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCekKondisiLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(panelCekKondisiLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(panelIdentitasPasien1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCekKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCekKondisiLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(40, 40, 40))
                    .addComponent(jLabel11))
                .addGap(37, 37, 37))
        );
        panelCekKondisiLayout.setVerticalGroup(
            panelCekKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCekKondisiLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panelCekKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelIdentitasPasien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCekKondisiLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)))
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polije/assets/Logo sunting.png"))); // NOI18N

        javax.swing.GroupLayout dasarLayout = new javax.swing.GroupLayout(dasar);
        dasar.setLayout(dasarLayout);
        dasarLayout.setHorizontalGroup(
            dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dasarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(panelCekKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dasarLayout.setVerticalGroup(
            dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dasarLayout.createSequentialGroup()
                .addComponent(panelCekKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(dasarLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tableKondisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKondisiMouseClicked
        // TODO add your handling code here:
      int row = tableKondisi.getSelectedRow();
      String id = tableKondisi.getValueAt(row, 1).toString();
      String namaIbu = tableKondisi.getValueAt(row, 2).toString();
      String namaAnak = tableKondisi.getValueAt(row, 3).toString();
      String tempatLahir = tableKondisi.getValueAt(row, 4).toString();
      String tanggalLahir = tableKondisi.getValueAt(row, 5).toString();
      String jenisKelamin = tableKondisi.getValueAt(row, 6).toString();
      String tinggi = tableKondisi.getValueAt(row, 7).toString();
      String umur = tableKondisi.getValueAt(row, 8).toString();
      int jkValue = 0;
      if(jenisKelamin.equals("Laki-laki")){
          jkValue = 0;
      }else{
          jkValue = 1;
      }
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        try {
            java.util.Date date = formater.parse(tanggalLahir);
               UpdateDelete updScrenn = new 
               UpdateDelete(namaIbu, namaAnak, tempatLahir,jkValue , umur, tinggi, date , id);
               updScrenn.setVisible(true);
               
        } catch (ParseException ex) {
            Logger.getLogger(CekKondisi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
     
      
    }//GEN-LAST:event_tableKondisiMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekKondisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekKondisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekKondisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekKondisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekKondisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dasar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelIdentitasPasien1;
    private javax.swing.JLabel logoIdentitasPasien1;
    private javax.swing.JPanel panelCekKondisi;
    private javax.swing.JPanel panelIdentitasPasien1;
    private javax.swing.JPanel panelLabelIdentitas1;
    private javax.swing.JTable tableKondisi;
    // End of variables declaration//GEN-END:variables
}
