/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package polije.views;

import java.awt.Image;
import javax.swing.JPanel;

/**
 *
 * @author bacht
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }
    
    public JPanel getPanelHome(){
        return this.panelHome;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelDasar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        panelIdentitasPasien = new javax.swing.JPanel();
        logoIdentitasPasien = new javax.swing.JLabel();
        panelLabelIdentitas = new javax.swing.JPanel();
        labelIdentitasPasien = new javax.swing.JLabel();
        panelIdentitasPasien1 = new javax.swing.JPanel();
        logoIdentitasPasien1 = new javax.swing.JLabel();
        panelLabelIdentitas1 = new javax.swing.JPanel();
        labelIdentitasPasien1 = new javax.swing.JLabel();
        panelIdentitasPasien2 = new javax.swing.JPanel();
        logoIdentitasPasien2 = new javax.swing.JLabel();
        panelLabelIdentitas2 = new javax.swing.JPanel();
        labelIdentitasPasien2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDasar.setBackground(new java.awt.Color(255, 255, 255));
        panelDasar.setPreferredSize(new java.awt.Dimension(1280, 720));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polije/assets/Logo sunting.png")));
        jLabel1.setPreferredSize(new java.awt.Dimension(640, 720));

        panelHome.setBackground(new java.awt.Color(4, 30, 65));
        panelHome.setPreferredSize(new java.awt.Dimension(640, 720));

        panelIdentitasPasien.setBackground(new java.awt.Color(66, 83, 109));
        panelIdentitasPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelIdentitasPasienMouseClicked(evt);
            }
        });

        logoIdentitasPasien.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/polije/assets/Identitas pasien.png")).getImage().getScaledInstance(155, 155, Image.SCALE_DEFAULT)));
        logoIdentitasPasien.setMaximumSize(new java.awt.Dimension(155, 155));
        logoIdentitasPasien.setMinimumSize(new java.awt.Dimension(155, 155));
        logoIdentitasPasien.setPreferredSize(new java.awt.Dimension(155, 155));

        labelIdentitasPasien.setBackground(new java.awt.Color(242, 255, 255));
        labelIdentitasPasien.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelIdentitasPasien.setText("Identitas Pasien");

        javax.swing.GroupLayout panelLabelIdentitasLayout = new javax.swing.GroupLayout(panelLabelIdentitas);
        panelLabelIdentitas.setLayout(panelLabelIdentitasLayout);
        panelLabelIdentitasLayout.setHorizontalGroup(
            panelLabelIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLabelIdentitasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelIdentitasPasien)
                .addGap(27, 27, 27))
        );
        panelLabelIdentitasLayout.setVerticalGroup(
            panelLabelIdentitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLabelIdentitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIdentitasPasien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelIdentitasPasienLayout = new javax.swing.GroupLayout(panelIdentitasPasien);
        panelIdentitasPasien.setLayout(panelIdentitasPasienLayout);
        panelIdentitasPasienLayout.setHorizontalGroup(
            panelIdentitasPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdentitasPasienLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panelIdentitasPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLabelIdentitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoIdentitasPasien, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelIdentitasPasienLayout.setVerticalGroup(
            panelIdentitasPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIdentitasPasienLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(logoIdentitasPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelLabelIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelIdentitasPasien1.setBackground(new java.awt.Color(66, 83, 109));
        panelIdentitasPasien1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelIdentitasPasien1MouseClicked(evt);
            }
        });

        logoIdentitasPasien1.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/polije/assets/Cek kondisi.png")).getImage().getScaledInstance(155, 155, Image.SCALE_DEFAULT)));
        logoIdentitasPasien1.setMaximumSize(new java.awt.Dimension(155, 155));
        logoIdentitasPasien1.setMinimumSize(new java.awt.Dimension(155, 155));
        logoIdentitasPasien1.setPreferredSize(new java.awt.Dimension(155, 155));

        labelIdentitasPasien1.setBackground(new java.awt.Color(242, 255, 255));
        labelIdentitasPasien1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelIdentitasPasien1.setText("Cek Kondisi");

        javax.swing.GroupLayout panelLabelIdentitas1Layout = new javax.swing.GroupLayout(panelLabelIdentitas1);
        panelLabelIdentitas1.setLayout(panelLabelIdentitas1Layout);
        panelLabelIdentitas1Layout.setHorizontalGroup(
            panelLabelIdentitas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLabelIdentitas1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelIdentitasPasien1)
                .addGap(35, 35, 35))
        );
        panelLabelIdentitas1Layout.setVerticalGroup(
            panelLabelIdentitas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLabelIdentitas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIdentitasPasien1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelIdentitasPasien1Layout = new javax.swing.GroupLayout(panelIdentitasPasien1);
        panelIdentitasPasien1.setLayout(panelIdentitasPasien1Layout);
        panelIdentitasPasien1Layout.setHorizontalGroup(
            panelIdentitasPasien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdentitasPasien1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panelIdentitasPasien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLabelIdentitas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoIdentitasPasien1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelIdentitasPasien1Layout.setVerticalGroup(
            panelIdentitasPasien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIdentitasPasien1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(logoIdentitasPasien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelLabelIdentitas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelIdentitasPasien2.setBackground(new java.awt.Color(66, 83, 109));
        panelIdentitasPasien2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelIdentitasPasien2MouseClicked(evt);
            }
        });

        logoIdentitasPasien2.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/polije/assets/Kebutuhan Gizi.png")).getImage().getScaledInstance(155, 155, Image.SCALE_DEFAULT)));
        logoIdentitasPasien2.setMaximumSize(new java.awt.Dimension(155, 155));
        logoIdentitasPasien2.setMinimumSize(new java.awt.Dimension(155, 155));
        logoIdentitasPasien2.setPreferredSize(new java.awt.Dimension(155, 155));

        labelIdentitasPasien2.setBackground(new java.awt.Color(242, 255, 255));
        labelIdentitasPasien2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        labelIdentitasPasien2.setText("Kebutuhan Gizi");

        javax.swing.GroupLayout panelLabelIdentitas2Layout = new javax.swing.GroupLayout(panelLabelIdentitas2);
        panelLabelIdentitas2.setLayout(panelLabelIdentitas2Layout);
        panelLabelIdentitas2Layout.setHorizontalGroup(
            panelLabelIdentitas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLabelIdentitas2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelIdentitasPasien2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLabelIdentitas2Layout.setVerticalGroup(
            panelLabelIdentitas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLabelIdentitas2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIdentitasPasien2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelIdentitasPasien2Layout = new javax.swing.GroupLayout(panelIdentitasPasien2);
        panelIdentitasPasien2.setLayout(panelIdentitasPasien2Layout);
        panelIdentitasPasien2Layout.setHorizontalGroup(
            panelIdentitasPasien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdentitasPasien2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(panelIdentitasPasien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLabelIdentitas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoIdentitasPasien2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelIdentitasPasien2Layout.setVerticalGroup(
            panelIdentitasPasien2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIdentitasPasien2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(logoIdentitasPasien2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelLabelIdentitas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(panelIdentitasPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(panelIdentitasPasien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(panelIdentitasPasien2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelIdentitasPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelIdentitasPasien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(panelIdentitasPasien2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout panelDasarLayout = new javax.swing.GroupLayout(panelDasar);
        panelDasar.setLayout(panelDasarLayout);
        panelDasarLayout.setHorizontalGroup(
            panelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDasarLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(740, Short.MAX_VALUE))
            .addGroup(panelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDasarLayout.createSequentialGroup()
                    .addContainerGap(634, Short.MAX_VALUE)
                    .addComponent(panelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        panelDasarLayout.setVerticalGroup(
            panelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDasarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDasarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelDasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelDasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panelIdentitasPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelIdentitasPasienMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new TambahPasien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelIdentitasPasienMouseClicked

    private void panelIdentitasPasien1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelIdentitasPasien1MouseClicked
        // TODO add your handling code here:
        CekKondisi cekKondisi = new CekKondisi();
        cekKondisi.setVisible(true);
    }//GEN-LAST:event_panelIdentitasPasien1MouseClicked


    private void panelIdentitasPasien1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelIdentitasPasien1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new CekKondisi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelIdentitasPasien1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelIdentitasPasien;
    private javax.swing.JLabel labelIdentitasPasien1;
    private javax.swing.JLabel labelIdentitasPasien2;
    private javax.swing.JLabel logoIdentitasPasien;
    private javax.swing.JLabel logoIdentitasPasien1;
    private javax.swing.JLabel logoIdentitasPasien2;
    private javax.swing.JPanel panelDasar;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelIdentitasPasien;
    private javax.swing.JPanel panelIdentitasPasien1;
    private javax.swing.JPanel panelIdentitasPasien2;
    private javax.swing.JPanel panelLabelIdentitas;
    private javax.swing.JPanel panelLabelIdentitas1;
    private javax.swing.JPanel panelLabelIdentitas2;
    // End of variables declaration//GEN-END:variables
}
