/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package polije.views;

/**
 *
 * @author bacht
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelConten = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        register = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        kebutuhanGizi = new javax.swing.JPanel();
        cekKondisi = new javax.swing.JPanel();
        identitasPasien = new javax.swing.JPanel();
        kebutuhanGizi06 = new javax.swing.JPanel();
        kebutuhanGizi911 = new javax.swing.JPanel();
        kebutuhanGizi1224 = new javax.swing.JPanel();
        kebetuhanGizi25 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(640, 734));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        panelConten.setBackground(new java.awt.Color(4, 30, 65));
        panelConten.setPreferredSize(new java.awt.Dimension(640, 734));
        panelConten.setLayout(new java.awt.CardLayout());

        login.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        panelConten.add(login, "card2");

        register.setBackground(new java.awt.Color(102, 255, 0));

        javax.swing.GroupLayout registerLayout = new javax.swing.GroupLayout(register);
        register.setLayout(registerLayout);
        registerLayout.setHorizontalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        registerLayout.setVerticalGroup(
            registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        panelConten.add(register, "card3");

        home.setBackground(new java.awt.Color(0, 51, 204));

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        panelConten.add(home, "card4");

        kebutuhanGizi.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout kebutuhanGiziLayout = new javax.swing.GroupLayout(kebutuhanGizi);
        kebutuhanGizi.setLayout(kebutuhanGiziLayout);
        kebutuhanGiziLayout.setHorizontalGroup(
            kebutuhanGiziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        kebutuhanGiziLayout.setVerticalGroup(
            kebutuhanGiziLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        panelConten.add(kebutuhanGizi, "card5");

        javax.swing.GroupLayout cekKondisiLayout = new javax.swing.GroupLayout(cekKondisi);
        cekKondisi.setLayout(cekKondisiLayout);
        cekKondisiLayout.setHorizontalGroup(
            cekKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        cekKondisiLayout.setVerticalGroup(
            cekKondisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        panelConten.add(cekKondisi, "card6");

        javax.swing.GroupLayout identitasPasienLayout = new javax.swing.GroupLayout(identitasPasien);
        identitasPasien.setLayout(identitasPasienLayout);
        identitasPasienLayout.setHorizontalGroup(
            identitasPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        identitasPasienLayout.setVerticalGroup(
            identitasPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        panelConten.add(identitasPasien, "card7");

        javax.swing.GroupLayout kebutuhanGizi06Layout = new javax.swing.GroupLayout(kebutuhanGizi06);
        kebutuhanGizi06.setLayout(kebutuhanGizi06Layout);
        kebutuhanGizi06Layout.setHorizontalGroup(
            kebutuhanGizi06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        kebutuhanGizi06Layout.setVerticalGroup(
            kebutuhanGizi06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        panelConten.add(kebutuhanGizi06, "card8");

        javax.swing.GroupLayout kebutuhanGizi911Layout = new javax.swing.GroupLayout(kebutuhanGizi911);
        kebutuhanGizi911.setLayout(kebutuhanGizi911Layout);
        kebutuhanGizi911Layout.setHorizontalGroup(
            kebutuhanGizi911Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        kebutuhanGizi911Layout.setVerticalGroup(
            kebutuhanGizi911Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        panelConten.add(kebutuhanGizi911, "card9");

        javax.swing.GroupLayout kebutuhanGizi1224Layout = new javax.swing.GroupLayout(kebutuhanGizi1224);
        kebutuhanGizi1224.setLayout(kebutuhanGizi1224Layout);
        kebutuhanGizi1224Layout.setHorizontalGroup(
            kebutuhanGizi1224Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        kebutuhanGizi1224Layout.setVerticalGroup(
            kebutuhanGizi1224Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        panelConten.add(kebutuhanGizi1224, "card10");

        javax.swing.GroupLayout kebetuhanGizi25Layout = new javax.swing.GroupLayout(kebetuhanGizi25);
        kebetuhanGizi25.setLayout(kebetuhanGizi25Layout);
        kebetuhanGizi25Layout.setHorizontalGroup(
            kebetuhanGizi25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        kebetuhanGizi25Layout.setVerticalGroup(
            kebetuhanGizi25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );

        panelConten.add(kebetuhanGizi25, "card11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelConten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelConten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cekKondisi;
    private javax.swing.JPanel home;
    private javax.swing.JPanel identitasPasien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel kebetuhanGizi25;
    private javax.swing.JPanel kebutuhanGizi;
    private javax.swing.JPanel kebutuhanGizi06;
    private javax.swing.JPanel kebutuhanGizi1224;
    private javax.swing.JPanel kebutuhanGizi911;
    private javax.swing.JPanel login;
    private javax.swing.JPanel panelConten;
    private javax.swing.JPanel register;
    // End of variables declaration//GEN-END:variables
}
