/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package polije.views;

import java.awt.Color;
import java.awt.Dimension;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import polije.service.PassienServiceImpl;
import polije.service.PassienServiceInterface;
import polije.util.HelperClass;

/**
 *
 * @author zam
 */
public class TambahPasien extends javax.swing.JFrame {

    private PassienServiceInterface service;
    

    /**
     * Creates new form Register
     */
    public TambahPasien() {
        this.service = new PassienServiceImpl();
        this.setMaximumSize(new Dimension(1280, 720));
        this.setResizable(false);
        this.setBackground(new Color(4, 30, 65));
        initComponents();
    }
    
    public JPanel getPanelRegister() {
        return this.panelRegister;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegister = new javax.swing.JPanel();
        panelNamaLengkap = new javax.swing.JPanel();
        logoNamalengkap = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        namaIbu_txt = new javax.swing.JTextField();
        panelNamaLengkap1 = new javax.swing.JPanel();
        logoNamalengkap1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ttlPasien_txt = new javax.swing.JTextField();
        jDate_tanggalLahirPasienTxt = new com.toedter.calendar.JDateChooser();
        panelNamaLengkap4 = new javax.swing.JPanel();
        logoNamalengkap4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jenisKelaminPasien_combo = new javax.swing.JComboBox<>();
        panelNamaLengkap6 = new javax.swing.JPanel();
        logoNamalengkap6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namaAnak_txt = new javax.swing.JTextField();
        btn_simpanPasien = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelNamaLengkap5 = new javax.swing.JPanel();
        logoNamalengkap5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tinggi_badan_txt = new javax.swing.JTextField();
        panelNamaLengkap7 = new javax.swing.JPanel();
        logoNamalengkap7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        umur_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(4, 30, 65));

        panelRegister.setBackground(new java.awt.Color(4, 30, 65));
        panelRegister.setPreferredSize(new java.awt.Dimension(640, 720));

        panelNamaLengkap.setBackground(new java.awt.Color(255, 255, 255));

        logoNamalengkap.setText("Nama Ibu");

        jLabel1.setText(":");

        namaIbu_txt.setBorder(null);

        javax.swing.GroupLayout panelNamaLengkapLayout = new javax.swing.GroupLayout(panelNamaLengkap);
        panelNamaLengkap.setLayout(panelNamaLengkapLayout);
        panelNamaLengkapLayout.setHorizontalGroup(
            panelNamaLengkapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNamaLengkapLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoNamalengkap)
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(namaIbu_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNamaLengkapLayout.setVerticalGroup(
            panelNamaLengkapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNamaLengkapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelNamaLengkapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoNamalengkap)
                    .addComponent(jLabel1)
                    .addComponent(namaIbu_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        panelNamaLengkap1.setBackground(new java.awt.Color(255, 255, 255));

        logoNamalengkap1.setText("TTL");

        jLabel2.setText(":");

        ttlPasien_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jDate_tanggalLahirPasienTxt.setDateFormatString("yyyy-MM-dd");
        jDate_tanggalLahirPasienTxt.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jDate_tanggalLahirPasienTxtHierarchyChanged(evt);
            }
        });
        jDate_tanggalLahirPasienTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jDate_tanggalLahirPasienTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDate_tanggalLahirPasienTxtFocusLost(evt);
            }
        });
        jDate_tanggalLahirPasienTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDate_tanggalLahirPasienTxtMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jDate_tanggalLahirPasienTxtMouseReleased(evt);
            }
        });
        jDate_tanggalLahirPasienTxt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jDate_tanggalLahirPasienTxtComponentShown(evt);
            }
        });

        javax.swing.GroupLayout panelNamaLengkap1Layout = new javax.swing.GroupLayout(panelNamaLengkap1);
        panelNamaLengkap1.setLayout(panelNamaLengkap1Layout);
        panelNamaLengkap1Layout.setHorizontalGroup(
            panelNamaLengkap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNamaLengkap1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoNamalengkap1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ttlPasien_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDate_tanggalLahirPasienTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        panelNamaLengkap1Layout.setVerticalGroup(
            panelNamaLengkap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNamaLengkap1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNamaLengkap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNamaLengkap1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelNamaLengkap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNamaLengkap1Layout.createSequentialGroup()
                                .addGroup(panelNamaLengkap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(logoNamalengkap1)
                                    .addComponent(jLabel2))
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNamaLengkap1Layout.createSequentialGroup()
                                .addComponent(ttlPasien_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(panelNamaLengkap1Layout.createSequentialGroup()
                        .addComponent(jDate_tanggalLahirPasienTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        panelNamaLengkap4.setBackground(new java.awt.Color(255, 255, 255));

        logoNamalengkap4.setText("Jenis Kelamin");

        jLabel5.setText(":");

        jenisKelaminPasien_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih jenis kelamin", "Laki-laki", "Perempuan" }));
        jenisKelaminPasien_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisKelaminPasien_comboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNamaLengkap4Layout = new javax.swing.GroupLayout(panelNamaLengkap4);
        panelNamaLengkap4.setLayout(panelNamaLengkap4Layout);
        panelNamaLengkap4Layout.setHorizontalGroup(
            panelNamaLengkap4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNamaLengkap4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoNamalengkap4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(66, 66, 66)
                .addComponent(jenisKelaminPasien_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelNamaLengkap4Layout.setVerticalGroup(
            panelNamaLengkap4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNamaLengkap4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelNamaLengkap4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoNamalengkap4)
                    .addComponent(jLabel5)
                    .addComponent(jenisKelaminPasien_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        panelNamaLengkap6.setBackground(new java.awt.Color(255, 255, 255));

        logoNamalengkap6.setText("Nama Anak");

        jLabel7.setText(":");

        namaAnak_txt.setBorder(null);

        javax.swing.GroupLayout panelNamaLengkap6Layout = new javax.swing.GroupLayout(panelNamaLengkap6);
        panelNamaLengkap6.setLayout(panelNamaLengkap6Layout);
        panelNamaLengkap6Layout.setHorizontalGroup(
            panelNamaLengkap6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNamaLengkap6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoNamalengkap6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(namaAnak_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelNamaLengkap6Layout.setVerticalGroup(
            panelNamaLengkap6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNamaLengkap6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelNamaLengkap6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelNamaLengkap6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logoNamalengkap6)
                        .addComponent(namaAnak_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        btn_simpanPasien.setText("Simpan");
        btn_simpanPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_simpanPasienMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(66, 83, 109));

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/zam/Desktop/joki/h-chid/H-Child/src/polije/assets/identitas_final_128.png")); // NOI18N

        jLabel4.setText("Identitas Pasien");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        panelNamaLengkap5.setBackground(new java.awt.Color(255, 255, 255));

        logoNamalengkap5.setText("Tinggi Badan");

        jLabel6.setText(":");

        tinggi_badan_txt.setBorder(null);

        javax.swing.GroupLayout panelNamaLengkap5Layout = new javax.swing.GroupLayout(panelNamaLengkap5);
        panelNamaLengkap5.setLayout(panelNamaLengkap5Layout);
        panelNamaLengkap5Layout.setHorizontalGroup(
            panelNamaLengkap5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNamaLengkap5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoNamalengkap5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tinggi_badan_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        panelNamaLengkap5Layout.setVerticalGroup(
            panelNamaLengkap5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNamaLengkap5Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(panelNamaLengkap5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoNamalengkap5)
                    .addComponent(jLabel6)
                    .addComponent(tinggi_badan_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        panelNamaLengkap7.setBackground(new java.awt.Color(255, 255, 255));

        logoNamalengkap7.setText("Umur");

        jLabel8.setText(":");

        umur_txt.setBorder(null);
        umur_txt.setEnabled(false);

        jLabel10.setText("Bulan");

        javax.swing.GroupLayout panelNamaLengkap7Layout = new javax.swing.GroupLayout(panelNamaLengkap7);
        panelNamaLengkap7.setLayout(panelNamaLengkap7Layout);
        panelNamaLengkap7Layout.setHorizontalGroup(
            panelNamaLengkap7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNamaLengkap7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoNamalengkap7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(umur_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(87, 87, 87))
        );
        panelNamaLengkap7Layout.setVerticalGroup(
            panelNamaLengkap7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNamaLengkap7Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(panelNamaLengkap7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoNamalengkap7)
                    .addComponent(jLabel8)
                    .addComponent(umur_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(7, 7, 7))
        );

        jButton1.setText("Hitung Umur");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRegisterLayout = new javax.swing.GroupLayout(panelRegister);
        panelRegister.setLayout(panelRegisterLayout);
        panelRegisterLayout.setHorizontalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_simpanPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panelNamaLengkap6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelNamaLengkap1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelNamaLengkap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelNamaLengkap4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelNamaLengkap5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegisterLayout.createSequentialGroup()
                            .addComponent(panelNamaLengkap7, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(panelRegisterLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegisterLayout.setVerticalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegisterLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(panelNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelNamaLengkap6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelNamaLengkap1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelNamaLengkap4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelNamaLengkap5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegisterLayout.createSequentialGroup()
                        .addComponent(panelNamaLengkap7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btn_simpanPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(333, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 720));

        jLabel9.setIcon(new javax.swing.ImageIcon("/home/zam/Desktop/joki/h-chid/H-Child/src/polije/assets/rsz_1logo_sunting_1.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel9)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisKelaminPasien_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisKelaminPasien_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisKelaminPasien_comboActionPerformed

    private void btn_simpanPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_simpanPasienMouseClicked
        // TODO add your handling code here:
       String namaAnak = namaAnak_txt.getText();
       String namaIbu = namaIbu_txt.getText();
       String tempatLahir = ttlPasien_txt.getText();
       int jenisKelamin = jenisKelaminPasien_combo.getSelectedIndex();
       java.util.Date dtBeforeConvert = jDate_tanggalLahirPasienTxt.getDate();
       String tinggi = tinggi_badan_txt.getText();
       String umur = umur_txt.getText();
        System.out.println(tinggi.equals(""));
        System.out.println(dtBeforeConvert);
        System.out.println(jenisKelamin);
        System.out.println(tempatLahir);
        System.out.println(tinggi);
        
       if(!namaAnak.equals("") && !namaIbu.equals("") && !tempatLahir.equals("") && jenisKelamin != 0 && dtBeforeConvert != null && !tinggi.equals("") && !umur.equals("")){
           try {
                int tinggiInt = Integer.parseInt(tinggi);
                int umurInt = Integer.parseInt(umur);
                java.sql.Date dt = new java.sql.Date(dtBeforeConvert.getDate());
                if(jenisKelamin == 0){
                    JOptionPane.showMessageDialog(null, "Harap Pilih Jenis Kelamin Terlebih Dahulu", "Terjadi Kesalahan", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    String jkValue = "";
                    if(jenisKelamin == 1){
                        jkValue = "Laki-laki";
                    }else{
                        jkValue = "Perempuan";
                    }
                   boolean isAdd =  this.service.addPasien(namaAnak, namaIbu, tempatLahir,jkValue , dt, tinggiInt , umurInt);
                   if(isAdd){
                        JOptionPane.showMessageDialog(null, "Berhasil Menambahkan data Passien", "Success", JOptionPane.INFORMATION_MESSAGE);
                   }else{
                       JOptionPane.showMessageDialog(null, "Gagal Menambahkan data Passien", "failed", JOptionPane.INFORMATION_MESSAGE);
                   }
                }
           } catch (NumberFormatException e) {
               System.out.println(umur);
               System.out.println(tinggi);
               JOptionPane.showMessageDialog(null, "Gagal Menambahkan data Passien , harap masukan angka pada tinggi atau umur", "failed", JOptionPane.INFORMATION_MESSAGE);
           }
           
       }else{
           JOptionPane.showMessageDialog(null, "Harap Isi semua field", "Terjadi Kesalahan", JOptionPane.INFORMATION_MESSAGE);
       } 
    }//GEN-LAST:event_btn_simpanPasienMouseClicked

    private void jDate_tanggalLahirPasienTxtHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jDate_tanggalLahirPasienTxtHierarchyChanged
        // TODO add your handling code here:
        System.out.println("asdasd");
    }//GEN-LAST:event_jDate_tanggalLahirPasienTxtHierarchyChanged

    private void jDate_tanggalLahirPasienTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDate_tanggalLahirPasienTxtMouseClicked
        // TODO add your handling code here:
        Date dt = jDate_tanggalLahirPasienTxt.getDate();
        System.out.println("active j date");
        if(dt != null){
           LocalDate localdate = HelperClass.convertToLocalDateViaSqlDate(dt);
           int umur = this.service.getAge(dt);
            System.out.println(umur);
            umur_txt.setText(String.valueOf(umur)+" bulan");
        }
    }//GEN-LAST:event_jDate_tanggalLahirPasienTxtMouseClicked

    private void jDate_tanggalLahirPasienTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDate_tanggalLahirPasienTxtFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jDate_tanggalLahirPasienTxtFocusGained

    private void jDate_tanggalLahirPasienTxtComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDate_tanggalLahirPasienTxtComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jDate_tanggalLahirPasienTxtComponentShown

    private void jDate_tanggalLahirPasienTxtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDate_tanggalLahirPasienTxtMouseReleased
        // TODO add your handling code here:
        System.out.println("asdasdsads");
    }//GEN-LAST:event_jDate_tanggalLahirPasienTxtMouseReleased

    private void jDate_tanggalLahirPasienTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDate_tanggalLahirPasienTxtFocusLost
        // TODO add your handling code here:
        System.out.println("asdasdlost");
    }//GEN-LAST:event_jDate_tanggalLahirPasienTxtFocusLost

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Date date = jDate_tanggalLahirPasienTxt.getDate();
       SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
       Calendar calendar = Calendar.getInstance();
       Date dtnow = calendar.getTime();
       String dateLahir =  formater.format(date);
       String dateNow = formater.format(dtnow);
        try {
            if(dateLahir.compareTo(dateNow) > 0){
            JOptionPane.showMessageDialog(null, "Harap Masukan tanggal lahir dengan benar", "information", JOptionPane.INFORMATION_MESSAGE);
        }else if(dateLahir.compareTo(dateNow) == 0){
                        JOptionPane.showMessageDialog(null, "Harap Masukan tanggal lampau", "information", JOptionPane.INFORMATION_MESSAGE);

        }
            
        else{
              if(date == null){
            JOptionPane.showMessageDialog(null, "Harap Masukan tanggl lahir terlebih dahulu", "information", JOptionPane.INFORMATION_MESSAGE);
        }else{
            int umur = this.service.getAge(date);
            System.out.println(umur);
            umur_txt.setText(String.valueOf(umur));
        }
        }
        } catch (NullPointerException e) {
                        JOptionPane.showMessageDialog(null, "Harap pilih tanggal lahir terlebih dahulu", "information", JOptionPane.INFORMATION_MESSAGE);
        }
      
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahPasien().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simpanPasien;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDate_tanggalLahirPasienTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jenisKelaminPasien_combo;
    private javax.swing.JLabel logoNamalengkap;
    private javax.swing.JLabel logoNamalengkap1;
    private javax.swing.JLabel logoNamalengkap4;
    private javax.swing.JLabel logoNamalengkap5;
    private javax.swing.JLabel logoNamalengkap6;
    private javax.swing.JLabel logoNamalengkap7;
    private javax.swing.JTextField namaAnak_txt;
    private javax.swing.JTextField namaIbu_txt;
    private javax.swing.JPanel panelNamaLengkap;
    private javax.swing.JPanel panelNamaLengkap1;
    private javax.swing.JPanel panelNamaLengkap4;
    private javax.swing.JPanel panelNamaLengkap5;
    private javax.swing.JPanel panelNamaLengkap6;
    private javax.swing.JPanel panelNamaLengkap7;
    private javax.swing.JPanel panelRegister;
    private javax.swing.JTextField tinggi_badan_txt;
    private javax.swing.JTextField ttlPasien_txt;
    private javax.swing.JTextField umur_txt;
    // End of variables declaration//GEN-END:variables
}
