/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package polije.views;

import java.awt.HeadlessException;
import java.util.Date;
import javax.swing.JOptionPane;
import polije.service.PassienServiceImpl;
import polije.service.PassienServiceInterface;
import repository.PasienRepositoryImpl;
import repository.PassienRepositoryInterface;

/**
 *
 * @author zam
 */
public class UpdateDelete extends javax.swing.JFrame {
    
    private PassienServiceInterface service;

    /**
     * Creates new form UpdateDelete
     */
    public UpdateDelete(String namaIbu , String namaAnak , String tempatLahir , int jenisKelamin , String umur , String tinggi , Date tanggalLahir , String id) {
        this.setResizable(false);
         this.service = new PassienServiceImpl();
        initComponents();
        this.editNamaIbu_txt.setText(namaIbu);
        this.namaAnakEdit_txt.setText(namaAnak);
        this.editTempatLahir_txt.setText(tempatLahir);
        this.jenisKelaminEdit_txt.setSelectedIndex(jenisKelamin);
        this.umurEdit.setText(umur);
        this.tinggiBadan_txt.setText(tinggi);
        this.tanggalLahirEdit.setDate(tanggalLahir);
        this.id.setText(id);
        this.id.setVisible(false);
    }

    public UpdateDelete(){
        this.setResizable(false);
        this.service = new PassienServiceImpl();
        initComponents();
        this.id.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editNamaIbu_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        editTempatLahir_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tinggiBadan_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namaAnakEdit_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        umurEdit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        simpanEdit = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jenisKelaminEdit_txt = new javax.swing.JComboBox<>();
        tanggalLahirEdit = new com.toedter.calendar.JDateChooser();
        id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Update Data Pasien");

        jLabel2.setText("Nama Ibu");

        jLabel3.setText("Tempat Lahir");

        editTempatLahir_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTempatLahir_txtActionPerformed(evt);
            }
        });

        jLabel4.setText("Tinggi Badan");

        tinggiBadan_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiBadan_txtActionPerformed(evt);
            }
        });

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Nama Anak");

        namaAnakEdit_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaAnakEdit_txtActionPerformed(evt);
            }
        });

        jLabel7.setText("Umur");

        jLabel8.setText("Tanggal Lahir");

        simpanEdit.setText("Simpan");
        simpanEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanEditMouseClicked(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("cancel");

        jenisKelaminEdit_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        tanggalLahirEdit.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jenisKelaminEdit_txt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tinggiBadan_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editNamaIbu_txt)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editTempatLahir_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6)
                                .addComponent(namaAnakEdit_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(umurEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tanggalLahirEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addGap(18, 18, 18)
                                .addComponent(simpanEdit)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton))
                            .addComponent(id, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(id))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editNamaIbu_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editTempatLahir_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tinggiBadan_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaAnakEdit_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(umurEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tanggalLahirEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simpanEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jenisKelaminEdit_txt))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editTempatLahir_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTempatLahir_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTempatLahir_txtActionPerformed

    private void tinggiBadan_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiBadan_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiBadan_txtActionPerformed

    private void namaAnakEdit_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaAnakEdit_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaAnakEdit_txtActionPerformed

    private void simpanEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanEditMouseClicked
        // TODO add your handling code here:
        
        try {
            String namaAnak = namaAnakEdit_txt.getText();
            String namaIbu = editNamaIbu_txt.getText();
            String tempatLahir = editTempatLahir_txt.getText();
            Date tanggalLahir = tanggalLahirEdit.getDate();
            String jenisKelamin = jenisKelaminEdit_txt.getSelectedItem().toString();
            String tinggi = tinggiBadan_txt.getText();
            String umut = umurEdit.getText();
            if(!namaAnak.equals("") && !namaIbu.equals("") && !tempatLahir.equals("")&&!jenisKelamin.equals("")&&!tinggi.equals("")&&!umut.equals("")&&tanggalLahir!=null){
              try {
                int umurValue = Integer.parseInt(umut);
                int tingiValue = Integer.parseInt(tinggi);
                int idValue = Integer.parseInt(id.getText());
                java.sql.Date dateAfter = new java.sql.Date(tanggalLahir.getTime());
                boolean isUpdate = this.service.updatePasien(namaAnak, namaIbu, tempatLahir, jenisKelamin, dateAfter, tingiValue, umurValue, idValue);
                if(isUpdate){
                    JOptionPane.showMessageDialog(null, "Berhasil memperbarui data", "success", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Gagal Update Data , Terjadi kesalahan server", "failed", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Harap isikan umur , tingin denan angka", "failed", JOptionPane.ERROR_MESSAGE);
            }  
            }else{
                JOptionPane.showMessageDialog(null, "Harap isikan semua field", "failed", JOptionPane.ERROR_MESSAGE);
            }
            
            
            
            
        } catch (NullPointerException e) {
                            JOptionPane.showMessageDialog(null, "Harap isikan semua field", "failed", JOptionPane.ERROR_MESSAGE);
            
        }
        
       
    }//GEN-LAST:event_simpanEditMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        String idValue = id.getText();
        boolean result = this.service.deletePasien(idValue);
        if(result){
              JOptionPane.showMessageDialog(null, "Berhasil Delete Data", "success", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();  
        }else{
                                JOptionPane.showMessageDialog(null, "Gagal delete Data , Terjadi kesalahan server", "failed", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField editNamaIbu_txt;
    private javax.swing.JTextField editTempatLahir_txt;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> jenisKelaminEdit_txt;
    private javax.swing.JTextField namaAnakEdit_txt;
    private javax.swing.JButton simpanEdit;
    private com.toedter.calendar.JDateChooser tanggalLahirEdit;
    private javax.swing.JTextField tinggiBadan_txt;
    private javax.swing.JTextField umurEdit;
    // End of variables declaration//GEN-END:variables
}
